---
- name: testing conditionals
  hosts: all
  remote_user: ec2-user
  become: yes

  vars:
    unicorn: true

  tasks:
    - name: don't install on debian machines
      yum :
        name: httpd
        state: latest
      when: (ansible_os_family == "RedHat" and ansible_distribution_major_version=="2")

    - name: are unicorns real or fake
      shell : echo "Unicorns are fake"
      when:  not unicorn

      #- fail:
      #  msg: "Unicorns require rainbow variable to be set"
      #when: rainbow is undefined

    - name: test to see if selinux is running
      shell: getenforce
      register: sestatus

    - name: configure selinux if not enforcing
      seboolean:
        name: mysql_connect_any
        state: true
        persistent: yes
      when: sestatus.rc != 0

    - name: checking systemd 
      shell: cat /var/log/messages
      register: log_output

    - name: next task
      shell: echo "Systemd known when we're doing ansible stuff"
      when: log_output.stdout.find('ansible') != 0
      register: shell_echo

    - debug:
        var: shell_echo

