---
- name: testing variable stuff
  hosts: all
  remote_user: ec2-user

  tasks:
    - name: get date on the server
      shell: date
      register: output

    - debug:
        msg: "The date is {{output.stdout}}"

    - debug:
        var: ansible_distribution_version
        #msg: "version: {{ansible_distribution_version}}"
        
    - name: group some machines together temporarily
      group_by:
        key: rhel_{{ansible_distribution_version}}
      register: group_result

    - debug: 
        var: group_result

         
