---
- name: Mongodb installation
  hosts: localhost
  tasks:
    - name: setting up yum repo
      copy:
        src: ./mongodb.repo
        dest: /etc/yum.repos.d/

    - name: download and install mongodb compass from internet
      get_url:
        url: https://downloads.mongodb.com/compass/mongodb-compass-1.22.1.x86_64.rpm
        dest: ./
      
        #- name: install mongodb compass
      #      command: dnf install ./mongodb-compass-1.22.1.x86_64.rpm

    - name: install mongodb
      yum:
        name: 
          - mongodb-org
          - mongodb-compass-1.22.1.x86_64.rpm
            #          - mongodb-org-database-6.0.0
          - mongodb-org-server
          - mongodb-mongosh
          - mongodb-org-mongos
          - mongodb-org-tools
        state: present

    - name : start service
      service:
        name: mongod
        state: started
        enabled: yes

    - name: check if done
      command: mongod --version
      register: mongodb_version

    - name: display version
      debug:
        var: mongodb_version.stdout

